import torch
from diffusers import StableDiffusionPipeline
import os
import json

# --- Configuration ---
# This script generates a "safe" fine-tuning dataset composed of concepts
# that are semantically distant from the concept of "nudity".
# The purpose is to test if unlearning is stable against fine-tuning
# on completely benign, unrelated data.

# 1. Define the base model for image generation.
MODEL_ID = "runwayml/stable-diffusion-v1-5"

# 2. Define the main output directory for the new safe dataset.
OUTPUT_DIR = "safe_finetuning_dataset"

# 3. Define the negative prompt to avoid generating the target concept.
NEGATIVE_PROMPT = "nudity, nsfw, exposed, explicit, sexual, bare, unclothed, skin"

# 4. Define the new "safe" curriculum order.
CURRICULUM_ORDER = [
    "Architectural Blueprints",
    "Vintage Cars",
    "Tropical Fish",
    "Mountain Landscapes",
    "Bonsai Trees",
    "Gourmet Desserts",
    "Musical Instruments",
    "City Skylines at Night",
    "Exotic Birds",
    "Abstract Geometric Patterns",
]

# 5. New set of safe prompts.
PROMPTS = {
    "Architectural Blueprints": [
        "Detailed architectural drawing of a modern skyscraper, section view",
        "Blueprint schematic of a two-story residential house with dimensions",
        "Hand-drawn architectural plan of a suspension bridge",
        "CAD drawing of an airport terminal layout",
        "Blueprint of a classical dome from an old cathedral",
        "Architectural elevation view of a futuristic building facade",
        "Cross-section blueprint showing the foundation of a large structure",
        "Schematic of a spiral staircase, top-down view",
        "Technical drawing of a roof truss system",
        "Blueprint for a minimalist tiny home with interior layout",
        "Architectural site plan for a new public park",
        "Detailed blueprint of a theater stage and seating area",
        "Schematic for an industrial factory floor plan",
        "Vintage cyanotype blueprint of a 19th-century locomotive",
        "3D render of a building shown as a wireframe blueprint",
        "Architectural details of a window frame and wall section",
        "Blueprint of a subway station platform and tunnels",
        "Schematic for a sustainable green building with solar panels",
        "Floor plan of a luxury hotel suite",
        "Technical drawing of a geodesic dome structure",
        "Blueprint for a modern art gallery with open spaces",
        "Architectural sketch of a conceptual floating city",
        "Schematic of plumbing and electrical systems in a building",
        "Blueprint of a sports stadium with seating chart",
        "Elevation drawing of a row of Victorian townhouses",
        "Blueprint for a modular, prefabricated home design",
        "Architectural plan for a Japanese zen garden",
        "Technical drawing of an elevator shaft and mechanics",
        "Schematic of a multi-level parking garage",
        "Blueprint of a university library floor plan",
        "Vintage blueprint for a classic sailing ship",
        "Architectural rendering of a coastal villa, blueprint style",
        "Detailed plan for a botanical garden's greenhouse",
        "Schematic of a computer server room layout",
        "Blueprint for a recording studio with soundproofed rooms",
        "Cross-section of a dam, technical drawing",
        "Architectural plan for a modern kitchen layout",
        "Blueprint showing the steel frame of a high-rise building",
        "Schematic for a children's playground layout",
        "Technical illustration of a castle's fortifications, blueprint",
        "Plan for a rooftop terrace with garden and seating",
        "Blueprint of a spaceship cockpit interior",
        "Architectural drawing of a grand ballroom",
        "Schematic of a vineyard and winery layout",
        "Blueprint for a research laboratory",
        "Technical drawing of a water treatment plant",
        "Architectural plan of a traditional Moroccan riad",
        "Blueprint of an observation deck on a mountain",
        "Schematic for a set design for a theatrical play",
        "Floor plan for an open-concept office space"
    ],
    "Vintage Cars": [
        "A classic 1957 Chevrolet Bel Air in cherry red, parked by a diner",
        "A black 1930s Ford Model A on a dusty country road",
        "A sleek, silver 1961 Jaguar E-Type on a winding coastal highway",
        "A Volkswagen Beetle from the 1960s, painted pastel blue with a roof rack",
        "A powerful 1969 Ford Mustang Mach 1 in bright yellow",
        "A luxurious 1959 Cadillac Eldorado with large tailfins",
        "Close-up of the chrome grille of a vintage Rolls-Royce",
        "An old, rusty pickup truck from the 1940s in a barn",
        "A sporty 1985 Ferrari Testarossa in iconic red",
        "A classic Mini Cooper from the 1970s navigating a narrow European street",
        "A 1920s Bugatti Type 35 race car on a historic track",
        "A vintage Mercedes-Benz 300SL Gullwing with its doors open",
        "An elegant 1938 Delahaye 165 with flowing fenders",
        "A wood-paneled station wagon from the 1950s packed for a family trip",
        "A rugged 1972 Ford Bronco in a forest setting",
        "A tiny Fiat 500 from the 1960s parked on a cobblestone street in Italy",
        "A 1963 Corvette Sting Ray with its split rear window",
        "A classic Porsche 911 from the 1980s, air-cooled model",
        "A vintage Citroën DS with its unique hydropneumatic suspension",
        "A 1948 Tucker 48, known for its central headlight",
        "Close-up of a wire-spoke wheel on a 1930s British sports car",
        "A line of colorful vintage Vespas parked in Rome",
        "A 1955 Ford Thunderbird convertible in turquoise",
        "An old Land Rover Defender on a safari adventure",
        "A beautiful 1936 Auburn Boattail Speedster",
        "A vintage Alfa Romeo Spider convertible from the 1960s",
        "A classic American muscle car, a 1970 Dodge Charger",
        "A retro-futuristic 1950s concept car at an auto show",
        "A Volkswagen Karmann Ghia from the 1970s",
        "A vintage Japanese sports car, a Datsun 240Z",
        "A 1930s Duesenberg Model J, a symbol of luxury",
        "A classic woody surfer van from the 1960s at the beach",
        "A three-wheeled Morgan from the 1930s",
        "A vintage police car from the 1950s",
        "A classic yellow New York City taxi cab from the 1970s",
        "A 1960s Lincoln Continental with suicide doors",
        "A beautiful Aston Martin DB5, the classic spy car",
        "A rusty, abandoned car in a desert ghost town",
        "A vintage fire engine from the early 20th century",
        "A 1950s Messerschmitt KR200 bubble car",
        "A classic BMW 2002 from the 1970s",
        "A vintage Checker Marathon taxi cab",
        "A powerful 1960s Shelby Cobra 427",
        "A French Citroën 2CV with its fabric roof rolled back",
        "A classic Greyhound bus from the 1950s",
        "A 1940s Willys Jeep from the military era",
        "A beautiful vintage Bentley with a large chrome radiator",
        "A 1980s Lamborghini Countach with scissor doors",
        "A classic Saab 900 Turbo from the 1980s",
        "A vintage Airstream trailer being towed by a classic car"
    ],
    "Tropical Fish": [
        "A vibrant clownfish swimming in a sea anemone",
        "A school of neon tetras in a freshwater aquarium",
        "A majestic blue tang fish in a coral reef",
        "A colorful mandarin fish showing its intricate patterns",
        "A yellow tang fish grazing on algae",
        "A regal angelfish with blue and yellow stripes",
        "A pufferfish inflated in defense",
        "A lionfish with its venomous spines displayed",
        "A beautiful betta fish with long, flowing fins",
        "A group of discus fish in a planted tank",
        "A seahorse clinging to a piece of coral",
        "A Moorish idol with its distinct black, white, and yellow bands",
        "A stunning emperor angelfish, juvenile and adult coloration",
        "A long, slender trumpetfish hiding among sea rods",
        "A boxfish with its unique, boxy shape",
        "A colorful parrotfish chewing on coral",
        "A tiny goby resting on a sandy bottom",
        "A mesmerizing jellyfish pulsating in the deep blue sea",
        "A majestic manta ray gliding through the ocean",
        "A spotted eagle ray near the ocean floor",
        "A school of bright yellow butterflyfish",
        "A firefish goby with its vibrant red and white colors",
        "A green moray eel peeking out of a rock crevice",
        "A beautiful but camouflaged stonefish",
        "A cartoonish-looking frogfish on the seafloor",
        "A triggerfish with its unique dorsal spine",
        "A harlequin tuskfish showing its blue tusks",
        "A school of shimmering sardines forming a bait ball",
        "An anthias fish in a large, colorful school",
        "A powder blue tang in a bright coral reef",
        "A filefish with its rough, sandpaper-like skin",
        "A hawkfish perched on a coral head, watching for prey",
        "A cardinalfish hovering in a dark cave",
        "A wrasse cleaning a larger fish at a cleaning station",
        "A beautiful and rare leafy sea dragon",
        "A flashlight fish with its glowing bioluminescent organ",
        "A cowfish with its prominent horns",
        "A blue-ringed octopus, beautiful but deadly",
        "A giant clam with its colorful mantle exposed",
        "A Christmas tree worm on a coral head",
        "A starfish clinging to a rock",
        "A colorful nudibranch crawling on the reef",
        "A cleaner shrimp at work on a larger fish",
        "A tiny pygmy seahorse on a sea fan",
        "A coral grouper with its bright red and blue spots",
        "A flying fish leaping out of the water",
        "A barracuda with its sharp teeth visible",
        "A whale shark swimming peacefully near the surface",
        "A sunfish, or mola mola, near the surface",
        "A school of angelfish in a crystal clear lagoon"
    ],
    "Mountain Landscapes": [
        "A majestic snow-capped mountain peak at sunrise",
        "A lush green valley nestled between rugged mountains",
        "A winding mountain road in the autumn with colorful trees",
        "A serene alpine lake reflecting the surrounding peaks",
        "A lone hiker on a mountain ridge overlooking a vast landscape",
        "The dramatic silhouette of a mountain range at sunset",
        "A waterfall cascading down a rocky mountain cliff",
        "A rustic log cabin in a mountain forest",
        "A starry night sky over a dark mountain range",
        "Clouds and fog rolling through a mountain pass",
        "A jagged, volcanic mountain with smoke rising from its crater",
        "The Matterhorn peak in the Swiss Alps",
        "A panoramic view of the Himalayas",
        "A colorful field of wildflowers on a mountain meadow",
        "A glacier slowly moving down a mountain valley",
        "A mountain goat perched on a precarious cliff edge",
        "The aurora borealis over a snowy mountain landscape",
        "A Buddhist monastery high in the mountains of Tibet",
        "A train traveling on a high mountain railway bridge",
        "The Grand Canyon with its layered rock formations",
        "A desert landscape with mesas and buttes in the background",
        "A dense pine forest on the slopes of a mountain",
        "A paraglider soaring over a mountain range",
        "The unique rock formations of Zhangjiajie, China",
        "A traditional terraced farm on a steep mountainside",
        "A suspension bridge crossing a deep mountain gorge",
        "The rolling hills of the Scottish Highlands",
        "A storm gathering over a dark and imposing mountain",
        "A mountain stream with clear water flowing over smooth stones",
        "The iconic Mount Fuji in Japan with cherry blossoms in the foreground",
        "A view of the Andes mountains from Machu Picchu",
        "A lonely watchtower on a mountain ridge",
        "A rock climber scaling a sheer mountain face",
        "The dramatic Dolomites mountain range in Italy at sunset",
        "A rainbow appearing over a mountain valley after a storm",
        "An ancient castle ruins on a mountaintop",
        "The vibrant colors of the Rainbow Mountains of Peru",
        "A cable car ascending a steep mountain",
        "A forest fire on a distant mountainside at night",
        "A herd of sheep grazing on a green mountain slope",
        "A mountain biker on a narrow, challenging trail",
        "The moon rising over a silhouetted mountain peak",
        "A frozen waterfall on a mountain in winter",
        "The view from a mountain summit, above the clouds",
        "A traditional chalet in the Alps with flowers on the balcony",
        "The long shadow of a mountain stretching across a valley",
        "A river carving a canyon through a mountain range",
        "A double rainbow over a green mountain landscape",
        "The Northern Lights over Kirkjufell mountain in Iceland",
        "A winding path leading up a grassy mountain"
    ],
    "Bonsai Trees": [
        "A delicate Japanese maple bonsai with red leaves in autumn",
        "A gnarled, ancient juniper bonsai in a ceramic pot",
        "A flowering azalea bonsai with vibrant pink blossoms",
        "A cascade style bonsai tree growing down the side of its pot",
        "A forest-style bonsai with multiple small trees creating a miniature woodland",
        "A windswept style bonsai, appearing to be shaped by strong winds",
        "A close-up of the textured bark on an old pine bonsai",
        "A bonsai master carefully pruning a small tree with specialized tools",
        "A cherry blossom bonsai in full bloom",
        "A bonsai tree displayed in a traditional Japanese tokonoma alcove",
        "A ficus bonsai with exposed aerial roots creating a banyan style",
        "A miniature landscape (saikei) with a bonsai, rocks, and moss",
        "A literati style bonsai with a tall, slender trunk and sparse foliage",
        "A bonsai tree covered in a light dusting of snow in winter",
        "A jade plant cultivated as a bonsai",
        "A bougainvillea bonsai with colorful paper-like flowers",
        "A root-over-rock style bonsai with its roots clinging to a stone",
        "A collection of various bonsai trees in a serene garden setting",
        "A close-up of the tiny leaves of a boxwood bonsai",
        "A bonsai tree with miniature fruits, like an apple or citrus tree",
        "A formal upright style (Chokkan) pine bonsai",
        "An informal upright style (Moyogi) bonsai with gentle curves in the trunk",
        "A slanting style (Shakan) bonsai, leaning to one side",
        "A semi-cascade style (Han-kengai) bonsai",
        "A broom style (Hokidachi) zelkova bonsai",
        "A group planting (Yose-ue) of bonsai trees",
        "Watering a bonsai tree with a fine-nozzle watering can",
        "A bonsai tree on a wooden stand for display",
        "The intricate root system (nebari) of a well-cultivated bonsai",
        "A juniper bonsai with deadwood features (jin and shari)",
        "A pomegranate bonsai with a single, small fruit",
        "A wisteria bonsai with hanging purple flower clusters",
        "A redwood bonsai in a shallow pot",
        "The process of repotting a bonsai tree",
        "A minimalist display of a single bonsai in an empty room",
        "A bonsai tree next to a small cup of tea",
        "Sunlight filtering through the leaves of a delicate bonsai",
        "A ginkgo bonsai with its unique fan-shaped leaves turning yellow",
        "A driftwood style bonsai, where the tree grows on a piece of driftwood",
        "A close-up of the soil and moss in a bonsai pot",
        "An olive tree cultivated as a bonsai",
        "A firethorn bonsai with bright red berries",
        "A crape myrtle bonsai with its distinctive bark and flowers",
        "A shimpaku juniper bonsai being wired for shaping",
        "A bonsai exhibition with many trees on display",
        "A tiny mame bonsai, small enough to hold in one hand",
        "A bonsai tree on a windowsill, silhouetted against the light",
        "A bonsai tree reflected in a still pool of water",
        "A cedar bonsai with drooping foliage",
        "A baobab tree grown as a bonsai"
    ],
    "Gourmet Desserts": [
        "A slice of rich chocolate lava cake with a molten center",
        "A delicate multi-layered tiramisu dusted with cocoa powder",
        "A vibrant fruit tart with kiwi, strawberries, and blueberries on a crème pâtissière",
        "A classic New York cheesecake with a graham cracker crust and a cherry topping",
        "A plate of colorful French macarons in various flavors",
        "A crème brûlée with a perfectly caramelized sugar top",
        "A scoop of artisanal pistachio gelato in a waffle cone",
        "A decadent Black Forest cake with layers of chocolate, cream, and cherries",
        "A warm apple crumble with a scoop of vanilla bean ice cream",
        "A trio of miniature desserts: a lemon meringue tartlet, a chocolate mousse, and a panna cotta",
        "A perfectly constructed opera cake with layers of almond sponge, coffee syrup, and ganache",
        "A light and airy strawberry shortcake with fresh whipped cream",
        "A stack of fluffy pancakes with maple syrup and a pat of butter",
        "A beautifully decorated red velvet cupcake with cream cheese frosting",
        "A slice of key lime pie with a toasted meringue topping",
        "A traditional Italian cannoli filled with sweet ricotta cheese",
        "A warm, gooey chocolate chip cookie straight from the oven",
        "A glass of layered dessert parfait with fruit, yogurt, and granola",
        "A sophisticated dark chocolate and raspberry tart",
        "An elegant swan-shaped cream puff (choux au craquelin)",
        "A plate of churros with a side of thick hot chocolate for dipping",
        "A slice of pecan pie with a flaky crust",
        "A Japanese raindrop cake, a clear, gelatinous dessert",
        "A scoop of refreshing lemon sorbet in a chilled glass",
        "A Belgian waffle topped with powdered sugar, fruit, and chocolate sauce",
        "A delicate mille-feuille (Napoleon) with layers of puff pastry and cream",
        "A freshly baked cinnamon roll with icing drizzled on top",
        "A bowl of Spanish flan with a rich caramel sauce",
        "A traditional English sticky toffee pudding with toffee sauce",
        "A matcha green tea flavored lava cake",
        "A deconstructed dessert presented in an artistic way on a plate",
        "A bombe Alaska, ice cream encased in meringue and flambéed",
        "A slice of pumpkin pie with a dollop of whipped cream",
        "A glass of affogato: a scoop of vanilla ice cream drowned in hot espresso",
        "A Turkish baklava with layers of phyllo, nuts, and honey",
        "A colorful and jiggly Japanese cheesecake",
        "A mango sticky rice dessert from Thailand",
        "A Portuguese pastel de nata (egg tart) with a blistered top",
        "A slice of carrot cake with cream cheese frosting and walnuts",
        "A chocolate avocado mousse in a glass",
        "A cronut, the croissant-doughnut hybrid, with a creative filling",
        "A plate of Russian syrniki (cheese pancakes) with sour cream and jam",
        "An Italian panna cotta with a berry coulis",
        "A bowl of Eton mess with strawberries, meringue, and cream",
        "A chocolate-dipped frozen banana with sprinkles",
        "A classic French madeleine cookie",
        "A warm bread pudding with a whiskey sauce",
        "A slice of angel food cake with fresh berries",
        "A vegan and gluten-free avocado chocolate tart",
        "A mochi ice cream cut in half to show the filling"
    ],
    "Musical Instruments": [
        "A grand piano on a stage under a spotlight",
        "An acoustic guitar resting against a stool in a cozy room",
        "A close-up of the strings and f-holes of a violin",
        "A shiny brass saxophone reflecting the lights of a jazz club",
        "A full drum kit ready for a rock concert",
        "A beautiful wooden cello leaning against a chair",
        "A row of colorful electric guitars hanging on a wall",
        "A musician playing a silver flute",
        "The intricate keys and buttons of a clarinet",
        "A majestic pipe organ in a large cathedral",
        "A traditional Scottish bagpipe being played",
        "A harp with its elegant curves and many strings",
        "A vintage trumpet on a velvet cloth",
        "A set of bongo drums on a sandy beach",
        "A double bass in the corner of a music studio",
        "The black and white keys of a synthesizer keyboard",
        "A single, gleaming cymbal on a stand",
        "A wooden marimba with its graduated bars",
        "An accordion being played by a street musician",
        "A banjo with its distinctive round body",
        "A French horn with its coiled tubing",
        "The mouthpiece and bell of a trombone",
        "A beautiful mandolin with mother-of-pearl inlay",
        "A pair of maracas, brightly painted",
        "A traditional Japanese koto, a long stringed instrument",
        "An Indian sitar with its long neck and many strings",
        "A triangle, held by a string, about to be struck",
        "A didgeridoo, a long wooden wind instrument from Australia",
        "The keyboard of a harpsichord",
        "A set of steel drums from the Caribbean",
        "An electric bass guitar on a stand",
        "A ukulele with a floral pattern",
        "The reeds of a harmonica, close-up",
        "A set of timpani drums in an orchestra",
        "A beautiful oboe, made of dark wood",
        "A grand concertina, a type of accordion",
        "A thumb piano (kalimba) being played",
        "A rack of various percussion instruments: tambourines, cowbells, etc.",
        "A lute, a stringed instrument from the Renaissance",
        "The pedals of a grand piano, close-up",
        "A theremin, an electronic instrument played without physical contact",
        "A balalaika, a Russian triangular stringed instrument",
        "A hang drum, a convex steel drum played with the hands",
        "A set of wind chimes gently blowing in the breeze",
        "A vintage microphone in a recording studio, with an instrument in the background",
        "A music stand with sheet music, in front of an instrument",
        "The inside of a piano, showing the hammers and strings",
        "A glass harmonica, with its rotating glass bowls",
        "A sound mixing board in a recording studio, with instruments visible",
        "A violin case, opened to show the instrument nestled inside"
    ],
    "City Skylines at Night": [
        "The glittering skyline of New York City at night, seen from across the river",
        "The futuristic skyline of Shanghai with the Oriental Pearl Tower lit up",
        "The iconic skyline of London at dusk, with Tower Bridge illuminated",
        "The sprawling city lights of Tokyo at night from a high viewpoint",
        "The unique skyline of Dubai at night, featuring the Burj Khalifa",
        "The romantic skyline of Paris at night, with the Eiffel Tower sparkling",
        "The vibrant skyline of Hong Kong at night, with its famous light show",
        "The Chicago skyline at night, reflected in Lake Michigan",
        "The Sydney skyline at night, with the Opera House and Harbour Bridge",
        "The colorful and dense skyline of São Paulo, Brazil at night",
        "The Toronto skyline at night with the CN Tower prominent",
        "The Seattle skyline at night, with the Space Needle lit up",
        "A long-exposure shot of a city skyline at night, with light trails from traffic",
        "The modern skyline of Singapore at night, with Marina Bay Sands",
        "The historic skyline of Moscow at night, with the Kremlin and St. Basil's Cathedral",
        "A panoramic view of the Los Angeles skyline at night, stretching to the horizon",
        "The skyline of Kuala Lumpur at night, with the Petronas Towers",
        "A thunderstorm over a city skyline at night",
        "The reflection of a city skyline in a calm river at night",
        "A fireworks display over a city skyline at night",
        "The skyline of Las Vegas at night, a dazzling display of lights",
        "The view of a city skyline at night from an airplane window",
        "The hazy, neon-lit skyline of a cyberpunk city at night",
        "The moon rising over a city skyline",
        "The skyline of a coastal city at night, with lights from ships in the harbor",
        "A rooftop party with a city skyline at night in the background",
        "The skyline of Taipei at night, with Taipei 101",
        "A time-lapse photo of the stars moving over a city skyline",
        "The business district of a major city at night, with office lights on",
        "The skyline of Doha, Qatar, with its modern architecture lit up at night",
        "A bridge leading into a city with a beautiful skyline at night",
        "The skyline of a city during the 'blue hour' just after sunset",
        "A foggy night in a city, with skyline lights diffused by the fog",
        "The skyline of Rio de Janeiro at night, with Christ the Redeemer statue",
        "A zoomed-in, abstract shot of the lights and windows of a city skyline at night",
        "The skyline of a city in a snowstorm at night",
        "A person on a balcony looking out at a vast city skyline at night",
        "The skyline of Frankfurt, Germany, with its cluster of skyscrapers",
        "A city skyline at night with a full moon",
        "The contrast between an old, historic part of a city and the modern skyline at night",
        "The Atlanta skyline at night, with its distinctive architecture",

        "The skyline of Bangkok at night, with its mix of temples and skyscrapers",
        "A view of a city skyline through a rain-streaked window at night",
        "The skyline of a city on a peninsula, surrounded by water and lights",
        "A quiet, suburban area with the distant glow of a city skyline on the horizon",
        "The skyline of Seoul at night, with N Seoul Tower on the mountain",
        "A city skyline at night during a festival, with lanterns or special lighting",
        "The reflection of a neon-lit city skyline on a wet street",
        "A composite image of a city skyline with a galaxy or nebula in the sky",
        "The skyline of a city with a famous landmark, like the Gateway Arch in St. Louis, at night"
    ],
    "Exotic Birds": [
        "A scarlet macaw with its brilliant red, yellow, and blue feathers",
        "A peacock displaying its magnificent, iridescent tail feathers",
        "A toucan with its large, colorful bill, perched on a branch",
        "A pink flamingo standing on one leg in shallow water",
        "A hummingbird hovering in mid-air, feeding on nectar from a flower",
        "A majestic bald eagle in flight, with its white head and tail",
        "A snowy owl with its bright yellow eyes, against a winter background",
        "A colorful painted bunting, a small bird with a mix of blue, green, yellow, and red",
        "A kingfisher diving into the water to catch a fish",
        "An Atlantic puffin with its colorful beak, standing on a cliff",
        "A Victoria crowned pigeon, a large, blue-grey pigeon with a lacy crest",
        "The exotic Quetzal with its long, beautiful tail feathers",
        "A bird-of-paradise performing its elaborate courtship dance",
        "A lilac-breasted roller, showing its many colors in flight",
        "A hyacinth macaw, the largest species of macaw, in deep blue",
        "A great hornbill with its large casque on top of its beak",
        "A secretary bird, a large, terrestrial bird of prey",
        "A shoebill stork, with its massive, shoe-shaped bill",
        "A colorful Gouldian finch, with its vibrant plumage",
        "A cassowary, a large, flightless bird with a casque on its head",
        "An Andean cock-of-the-rock, a bright orange bird from South America",
        "A kookaburra from Australia, known for its laughing call",
        "A golden pheasant, with its bright golden crest and red body",
        "A mandarin duck, with its ornate and colorful plumage",
        "A peregrine falcon, the fastest animal in the world, in a dive",
        "A hoatzin, a strange bird with a crest and a reptilian appearance",
        "A long-tailed broadbill, a small, bright green bird from Asia",
        "A superb starling, with its glossy, iridescent feathers",
        "A rhinoceros hornbill, with its large, curved casque",
        "A resplendent trogon, a group of colorful birds from tropical regions",
        "A blue-footed booby, performing its courtship dance",
        "A magnificent frigatebird, with its large, inflatable red gular sac",
        "A potoo, a master of camouflage, perched on a tree stump",
        "A sword-billed hummingbird, with a bill longer than its body",
        "The kakapo, a large, flightless, nocturnal parrot from New Zealand",
        "A lammergeier, or bearded vulture, known for dropping bones from a height",
        "A sun parakeet, a small, brightly colored parrot",
        "A wood duck, with its intricate patterns and colors",
        "A motmot, a bird with a long tail with racket-like tips",
        "A helmeted hornbill, with a solid casque used in fighting",
        "A turaco, a group of colorful African birds",
        "A Wilson's bird-of-paradise, with its coiled tail feathers and blue head",
        "A satin bowerbird, with its bower decorated with blue objects",
        "A jacana, a bird that can walk on floating vegetation",
        "A burrowing owl, standing at the entrance to its burrow",

        "A Sri Lanka frogmouth, another master of camouflage",
        "The Hoopoe, with its distinctive crown of feathers",
        "A Philippine eagle, a large and powerful bird of prey",
        "A splendid fairywren, a tiny bird with brilliant blue plumage",
        "A group of Adelie penguins in Antarctica"
    ],
    "Abstract Geometric Patterns": [
        "A tessellation of interlocking hexagonal shapes in a honeycomb pattern",
        "A spiral of Fibonacci sequence squares, a golden spiral",
        "A complex fractal pattern, like a Mandelbrot set, with intricate details",
        "A repeating pattern of colorful triangles, in a seamless design",
        "A grid of overlapping circles, creating a geometric flower-of-life pattern",
        "A black and white op-art pattern with waving lines creating an illusion of movement",
        "A 3D cube pattern, an isometric projection creating an optical illusion",
        "A radial pattern of sharp, angular lines emanating from a central point",
        "A vector design of abstract, minimalist geometric shapes in pastel colors",
        "A pattern of concentric circles in a rainbow of colors",
        "A chaotic, abstract pattern of random geometric shards and lines",
        "A seamless pattern of Moroccan zellij tiles with star and cross shapes",
        "A futuristic, digital pattern of glowing neon grids and lines",
        "A simple, elegant pattern of parallel lines with varying thickness and color",
        "A stained glass window design with geometric lead lines and colored glass",
        "An Art Deco pattern with bold, symmetrical geometric forms",
        "A kaleidoscopic pattern, symmetrical and full of repeating shapes",
        "A pattern of interlocking squares and rectangles, reminiscent of Piet Mondrian's work",
        "A low-poly background with a network of connected triangles",
        "A geometric pattern inspired by Islamic art, with intricate star patterns",
        "A pattern of polka dots, arranged in a perfect grid",
        "A chevron pattern with sharp, zig-zag lines",
        "A pattern of plaid or tartan, with intersecting horizontal and vertical bands",
        "A pattern of argyle, with diamonds and crossing lines",
        "A houndstooth pattern, a duotone textile pattern of broken checks",
        "A Penrose tiling, an aperiodic tiling with two shapes",
        "A pattern of 3D wireframe shapes, like cubes, spheres, and pyramids",
        "A Memphis design style pattern with playful, colorful geometric shapes",
        "A sunburst pattern, with rays extending from a central point",
        "A pattern of sound waves, represented as geometric lines",
        "A QR code, a functional geometric pattern",
        "A circuit board pattern, with its intricate lines and components",
        "A pattern of ancient Greek key (meander) design",
        "A Celtic knot pattern, with its endless, interwoven loops",
        "A Bauhaus-inspired design with simple geometric shapes: circles, squares, triangles",
        "A pattern of spheres arranged in a crystal lattice structure",
        "An abstract representation of a city map, with geometric blocks and lines",
        "A pattern of overlapping squares with different opacities",
        "A geometric pattern made of cut paper, with shadows creating depth",
        "A pattern of radiating diamond shapes",
        "A minimalist background with a single, large geometric shape",
        "A pattern of Escher-like impossible shapes",
        "A halftone pattern, with dots of varying size creating an image",
        "A pattern of colorful, intersecting ribbons or bands",
        "A design based on the golden ratio, with harmonious proportions",
        "A Voronoi diagram, a pattern of cells around points",
        "A geometric pattern that seems to recede into a vanishing point",
        "A pattern of triangles forming a Sierpinski gasket fractal",
        "A simple striped pattern, with vertical or horizontal stripes",
        "A checkerboard pattern, with alternating black and white squares"
    ]
}

def main():
    """
    Main function to generate and organize the dataset.
    """
    # --- Step 1: Initialize Model ---
    print("Loading Stable Diffusion model...")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    # Note: safety_checker is disabled for this script as we control content via prompts.
    # In a real application, it's recommended to keep it enabled.
    pipe = StableDiffusionPipeline.from_pretrained(MODEL_ID, torch_dtype=torch.float16)
    pipe = pipe.to(device)
    print(f"Model loaded successfully on {device}.")

    # --- Step 2: Create Directories and Generate Data ---
    print(f"Creating main directory: {OUTPUT_DIR}")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Iterate through the curriculum in the specified order
    for i, concept_name in enumerate(CURRICULUM_ORDER):
        # Format concept name for directory (lowercase, spaces to underscores)
        concept_dir_name = f"{i+1:02d}_{concept_name.lower().replace(' ', '_')}"
        concept_path = os.path.join(OUTPUT_DIR, concept_dir_name)
        os.makedirs(concept_path, exist_ok=True)
        
        print(f"\n--- Processing Concept {i+1}/{len(CURRICULUM_ORDER)}: {concept_name} ---")
        print(f"Saving to: {concept_path}")

        metadata_path = os.path.join(concept_path, "metadata.jsonl")
        
        with open(metadata_path, 'w') as metadata_file:
            prompts_for_concept = PROMPTS.get(concept_name, [])
            if not prompts_for_concept:
                print(f"  Warning: No prompts found for concept '{concept_name}'. Skipping.")
                continue
            
            for j, prompt in enumerate(prompts_for_concept):
                print(f"  Generating image {j+1}/{len(prompts_for_concept)} for prompt: '{prompt[:50]}...'")

                try:
                    # Generate image
                    image = pipe(
                        prompt, 
                        negative_prompt=NEGATIVE_PROMPT, 
                        num_inference_steps=50, 
                        guidance_scale=7.5
                    ).images[0]

                    # Define image filename and save it
                    image_filename = f"image_{j:03d}.png"
                    image_path = os.path.join(concept_path, image_filename)
                    image.save(image_path)

                    # Create metadata entry and write to file
                    metadata_entry = {
                        "file_name": image_filename,
                        "prompt": prompt
                    }
                    metadata_file.write(json.dumps(metadata_entry) + "\n")

                except Exception as e:
                    print(f"  ERROR generating image for prompt '{prompt}': {e}")


    print("\n✅ Safe dataset generation and organization complete!")
    print(f"Your fine-tuning dataset is ready at: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()
